CLASS zcl_ztxc_service_examp_mpc_ext DEFINITION
  PUBLIC
  INHERITING FROM zcl_ztxc_service_examp_mpc
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_ZTXC_SERVICE_EXAMP_MPC_EXT IMPLEMENTATION.
ENDCLASS.
