CLASS zcl_ztxc_service_examp_dpc_ext DEFINITION
  PUBLIC
  INHERITING FROM zcl_ztxc_service_examp_dpc
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_ZTXC_SERVICE_EXAMP_DPC_EXT IMPLEMENTATION.
ENDCLASS.
